export enum IpcChannels {
  OPEN_FILE_DIALOG = "open-file-dialog",
  SELECTED_FILE = "selected-file",
  UPLOAD_DATA_TO_DATABASE = "upload-data-to-database",
  DELETE_DATA_IN_DATABASE = "delete-data-in-database",
  GET_ALL_DATA = "get-all-data",
  IS_DATA_EXIST = "is-data-exist",
  UPLOAD_COMPLETE = "upload-complete",
  START_ROLLING = "start-rolling",
  SET_A_WINNER = "set-a-winner",
  ADD_PRIZE = "add-prize",
  GET_PRIZE = "get-prize",
  EDIT_PRIZE = "edit-prize",
  DELETE_PRIZE = "delete-prize",
}
