export const provinces = [
    { id: 'Aceh', name: 'Aceh' },
    { id: 'Sumatera Utara', name: 'Sumatera Utara' },
    { id: 'Sumatera Barat', name: 'Sumatera Barat' },
    { id: 'Riau', name: 'Riau' },
    { id: 'Jambi', name: 'Jambi' },
    { id: 'Sumatera Selatan', name: 'Sumatera Selatan' },
    { id: 'Bengkulu', name: 'Bengkulu' },
    { id: 'Lampung', name: 'Lampung' },
    { id: 'Kepulauan Bangka Belitung', name: 'Kepulauan Bangka Belitung' },
    { id: 'Kepulauan Riau', name: 'Kepulauan Riau' },
    { id: 'DKI Jakarta', name: 'DKI Jakarta' },
    { id: 'Jawa Barat', name: 'Jawa Barat' },
    { id: 'Jawa Tengah', name: 'Jawa Tengah' },
    { id: 'DI Yogyakarta', name: 'DI Yogyakarta' },
    { id: 'Jawa Timur', name: 'Jawa Timur' },
    { id: 'Banten', name: 'Banten' },
    { id: 'Bali', name: 'Bali' },
    { id: 'Nusa Tenggara Barat', name: 'Nusa Tenggara Barat' },
    { id: 'Nusa Tenggara Timur', name: 'Nusa Tenggara Timur' },
    { id: 'Kalimantan Barat', name: 'Kalimantan Barat' },
    { id: 'Kalimantan Tengah', name: 'Kalimantan Tengah' },
    { id: 'Kalimantan Selatan', name: 'Kalimantan Selatan' },
    { id: 'Kalimantan Timur', name: 'Kalimantan Timur' },
    { id: 'Kalimantan Utara', name: 'Kalimantan Utara' },
    { id: 'Sulawesi Utara', name: 'Sulawesi Utara' },
    { id: 'Sulawesi Tengah', name: 'Sulawesi Tengah' },
    { id: 'Sulawesi Selatan', name: 'Sulawesi Selatan' },
    { id: 'Sulawesi Tenggara', name: 'Sulawesi Tenggara' },
    { id: 'Gorontalo', name: 'Gorontalo' },
    { id: 'Sulawesi Barat', name: 'Sulawesi Barat' },
    { id: 'Maluku', name: 'Maluku' },
    { id: 'Maluku Utara', name: 'Maluku Utara' },
    { id: 'Papua', name: 'Papua' },
    { id: 'Papua Barat', name: 'Papua Barat' }
  ];